### PR TITLE
added support for sublimetext (stdin/filename handling)

### PR DESCRIPTION
**Pull request by iham**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Maybe it'd be a good idea to use [flake8-polyfill](https://gitlab.com/pycqa/flake8-polyfill) for this so it stays compatible to older flake8 versions?

**Comment by gforcada** [comment]
@The-Compiler I see the point, but we are talking about QA tools, not something needed for production projects, but rather on CI.

With this in mind I would rather keep dependencies low and just tell on the README that since version X.X is compatible with flake8 X.X and newer versions only on flake8 Y.Y.

At least myself, if I'm bumping flake8 I would do so on the full QA stack rather than just one or another.

**Comment by The-Compiler** [comment]
FWIW I'm still stuck with flake8 < 3.0 because of [flake8-putty](https://pypi.python.org/pypi/flake8-putty) not being ported and flake8 [not having per-file ignores](https://gitlab.com/pycqa/flake8/issues/89).

I'm fine with pinning flake8-deprecated to an older version though, I've had to do the same for other plugins too.

**Comment by gforcada** [comment]
@iham I just released it as version 1.2, would you mind giving it a try and checking if it works as expected for you? Thanks in advance!

**Pull request merged**
