### PR TITLE
Fix UnicodeDecodeError if system locale is not UTF-8

### PR DESCRIPTION
**Pull request by sshishov**
Fix for unicode error

### CODE REVIEW

**Comment by gforcada** [comment]
@sshishov  thanks for using flake8-deprecated and reporting the issues you find with it!

I will have a look in the following days and make a release right after merging it.

**Comment by gforcada** [comment]
@sshishov I just released version 1.2.1, would you mind giving it a try?

**Comment by sshishov** [comment]
@gforcada I will try it tomorrow and give you feedback.

**Comment by sshishov** [comment]
@gforcada it is working great, already integrated this version to my repo 👍

**Pull request merged**
