### PR TITLE
Require flake8 > 3.0

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by The-Compiler** [comment]
hmm - it seems to work fine with flake8 2.6.2, no?

**Comment by gforcada** [comment]
@The-Compiler most probably, but as I'm maintaining quite a few flake8 extensions and I already had to port some of them to flake8 > 3.0 I prefer to make all of them 3.0 complain.

I just found out that the last released version is **not** compatible with flake8 > 3.0: https://github.com/gforcada/flake8-deprecated/commit/6445409d6912e1df54a65b3d3904fbc89c2e789f

**Comment by gforcada** [comment]
@The-Compiler do you have any specific reason not to update to flake8 > 3.0? Given some arguments on not being able to do so I would consider keeping compatibility

**Comment by The-Compiler** [comment]
I'm waiting for [hacking](https://pypi.python.org/pypi/hacking) and https://github.com/jayvdb/flake8-putty/issues/14 (or per-file rule ignoring in flake8 core).

I could probably live without the former (as it's mostly covered by pylint), but I really need the latter.

**Comment by gforcada** [comment]
@The-Compiler fair enough, as I'm not really plan to change much if at all (aside of compatibility with flake8 > 3.0) the code, it will be safe to use the previous version anyway.

**Pull request merged**
